package com.example.fyprojectnew;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.constraintlayout.widget.ConstraintLayout;
import android.annotation.SuppressLint;
import android.os.Bundle;
import android.util.Log;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.Toast;
import com.gkemon.XMLtoPDF.PdfGenerator;
import com.gkemon.XMLtoPDF.PdfGeneratorListener;
import com.gkemon.XMLtoPDF.model.FailureResponse;
import com.gkemon.XMLtoPDF.model.SuccessResponse;

public class CheckGenerate extends AppCompatActivity {
    ConstraintLayout cheque;
    private PdfGenerator.XmlToPDFLifecycleObserver xmlToPDFLifecycleObserver;
 @SuppressLint("MissingInflatedId")
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_check_generate);
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        getSupportActionBar().setTitle("Cheque Page");
        cheque=(ConstraintLayout) findViewById(R.id.cheque);

     xmlToPDFLifecycleObserver = new PdfGenerator.XmlToPDFLifecycleObserver(this);
     getLifecycle().addObserver(xmlToPDFLifecycleObserver);
    }

    /* Toolbar Menu Action Perform :- */
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.cheque_menue_options,menu);
        MenuItem menuItem1=menu.findItem(R.id.share);
        MenuItem menuItem2=menu.findItem(R.id.download);
        return super.onCreateOptionsMenu(menu);
    }

    @Override
    public boolean onOptionsItemSelected(@NonNull MenuItem item) {
        if (item.getItemId()== R.id.share){
        }
        else if(item.getItemId() == R.id.download ){
            Log.d("Msg", "Error");

           /* Online PDF File Generator :- */
            PdfGenerator.getBuilder()
                    .setContext(CheckGenerate.this)
                    .fromLayoutXMLSource()
                    .fromLayoutXML(R.layout.activity_check_generate)
                    /* "fromLayoutXML()" takes array of layout resources.
                     * You can also invoke "fromLayoutXMLList()" method here which takes list of layout resources instead of array. */
                    .setFileName("Test-PDF")
                    /* It is file name */
                    .actionAfterPDFGeneration(PdfGenerator.ActionAfterPDFGeneration.SHARE)
                    .savePDFSharedStorage(xmlToPDFLifecycleObserver)
                    /*If you want to save your pdf in shared storage (where other apps can also see your pdf even after the app is uninstall).
                     * You need to pass an xmt to pdf lifecycle observer by the following method. To get complete overview please see the MainActivity of 'sample' folder */
                    .build(new PdfGeneratorListener() {
                        @Override
                        public void onFailure(FailureResponse failureResponse) {
                            super.onFailure(failureResponse);
                            Log.d("error",failureResponse.getErrorMessage());
                            Toast.makeText(CheckGenerate.this,failureResponse.getErrorMessage(),Toast.LENGTH_LONG).show();
                            /* If pdf is not generated by an error then you will findout the reason behind it
                             * from this FailureResponse. */
                        }
                        @Override
                        public void onStartPDFGeneration() {
                            /*When PDF generation begins to start*/
                        }
                        @Override
                        public void onFinishPDFGeneration() {
                            /*When PDF generation is finished*/
                        }
                        @Override
                        public void showLog(String log) {
                            super.showLog(log);
                            /*It shows logs of events inside the pdf generation process*/
                        }
                        @Override
                        public void onSuccess(SuccessResponse response) {
                            super.onSuccess(response);
                            Toast.makeText(CheckGenerate.this,"Success",Toast.LENGTH_LONG).show();
                            /* If PDF is generated successfully then you will find SuccessResponse
                             * which holds the PdfDocument,File and path (where generated pdf is stored)*/
                        }
                    });
        }
        return super.onOptionsItemSelected(item);
    }

    /*Back Option :- */
    @Override
    public boolean onSupportNavigateUp() {
        onBackPressed();
        return super.onSupportNavigateUp();
    }
}